# Tarefa 02

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os tutores
- Divirta-se :)

## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [2]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [3]:
# 1) Seu código aqui

per_acertos_mat = (df_mat/24)*100

per_acertos_por = (df_por/18)*100

per_acertos_geo = (df_por/8)*100

per_acertos_ing = (df_por/8)*100

per_acertos_his = (df_por/8)*100

per_acertos_fis = (df_por/12)*100

per_acertos_qui = (df_por/12)*100

In [4]:
# 2) Seu código aqui

total_de_acertos = df_mat + df_por + df_geo + df_ing + df_his + df_fis + df_qui

total_de_acertos

    Qt_acertos
0           35
1           48
2           50
3           32
4           30
..         ...
95          34
96          27
97          40
98          40
99          42

[100 rows x 1 columns]

In [5]:
# 3) Seu código aqui

per_acertos = ((total_de_acertos/90)*100).round(2)

per_acertos

    Qt_acertos
0        38.89
1        53.33
2        55.56
3        35.56
4        33.33
..         ...
95       37.78
96       30.00
97       44.44
98       44.44
99       46.67

[100 rows x 1 columns]

In [6]:
# 4) Seu código aqui

acertos_maior_45 = total_de_acertos['Qt_acertos'] > 45

acertos_maior_45.sum()

31

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [7]:
# 1) Seu código aqui

# Transformando em um único DataFrame

#Matemática

df_mat['Matemática'] = df_mat['Qt_acertos']

df_mat.drop(['Qt_acertos'], axis='columns', inplace = True)

#Português

df_por['Português'] = df_por['Qt_acertos']

df_por.drop(['Qt_acertos'], axis='columns', inplace = True)

#Geografia

df_geo['Geografia'] = df_geo['Qt_acertos']

df_geo.drop(['Qt_acertos'], axis='columns', inplace = True)

# Inglês

df_ing['Inglês'] = df_ing['Qt_acertos']

df_ing.drop(['Qt_acertos'], axis='columns', inplace = True)

# História

df_his['História'] = df_his['Qt_acertos']

df_his.drop(['Qt_acertos'], axis='columns', inplace = True)

# Física

df_fis['Física'] = df_fis['Qt_acertos']

df_fis.drop(['Qt_acertos'], axis='columns', inplace = True)

# Química

df_qui['Química'] = df_qui['Qt_acertos']

df_qui.drop(['Qt_acertos'], axis='columns', inplace = True)

In [8]:
df_concat = pd.concat([df_mat, df_por, df_geo, df_ing, df_his, df_fis, df_qui], axis=1, join='outer')

df_concat

    Matemática  Português  Geografia  Inglês  História  Física  Química
0            6          7          7       3         1       8        3
1           19         10          0       0         0      11        8
2           14         16          0       5         7       4        4
3           10          7          3       4         0       0        8
4            7          2          2       7         0       9        3
..         ...        ...        ...     ...       ...     ...      ...
95           6          4          7       1         4       9        3
96           8          1          4       6         1       4        3
97          23          5          0       2         4       1        5
98           0         10          3       1         5      10       11
99          11         15          0       1         6       7        2

[100 rows x 7 columns]

In [9]:
# 1) Seu código aqui

df_desc_mat = df_concat[df_concat['Matemática'] == 0]
          
df_desc_fis = df_concat[df_concat['Física'] == 0]
          
df_desc_qui = df_concat[df_concat['Química'] == 0]

In [10]:
# Dataframe com os desqualificados

df_desclassificados = df_concat[(df_concat['Matemática'] == 0).__or__ (df_concat['Física'] == 0).__or__(df_concat['Química'] == 0)]
          

df_desclassificados

    Matemática  Português  Geografia  Inglês  História  Física  Química
3           10          7          3       4         0       0        8
6            6          0          7       7         5       0        4
10          10          8          3       2         1       7        0
12          20          8          3       7         1       0        3
14           7         11          1       7         1       4        0
20          23         11          6       5         6       2        0
25           0          4          7       4         0       4        8
26          11         14          6       2         7       0        0
27          21         13          1       5         7       3        0
33          14          8          0       5         6       6        0
35          11         14          6       3         3       0       11
49           8          1          1       0         1       0        8
56           7          6          7       5         6       0        8
65           1          8          2       4         3       0        6
66           5          4          3       6         3       0       10
72          11         16          3       4         7       0        9
73           1         16          2       4         3       0       11
74           9         11          0       7         5       7        0
84          15          1          0       5         1       0        4
89          23         11          7       7         6       9        0
92          14         10          1       6         1       8        0
94           0          5          2       6         1       3        8
98           0         10          3       1         5      10       11

In [11]:
# 2) Seu código aqui

df_desclassificados.shape[0]

23

In [12]:
# 3) Seu código aqui

# Média em história

df_desclassificados['História'].mean()

3.4347826086956523

In [13]:
# Média em geografia

df_desclassificados['Geografia'].mean()

3.217391304347826

In [14]:
# 4) Dataframe com os desqualificados

df_class = df_concat[(df_concat['Matemática'] > 0) & (df_concat['Física'] > 0) & (df_concat['Química'] > 0)]
          
df_class

    Matemática  Português  Geografia  Inglês  História  Física  Química
0            6          7          7       3         1       8        3
1           19         10          0       0         0      11        8
2           14         16          0       5         7       4        4
4            7          2          2       7         0       9        3
5           20          2          5       3         2       9        9
..         ...        ...        ...     ...       ...     ...      ...
93          12         16          5       5         6       6        6
95           6          4          7       1         4       9        3
96           8          1          4       6         1       4        3
97          23          5          0       2         4       1        5
99          11         15          0       1         6       7        2

[77 rows x 7 columns]

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?

In [15]:
arquivo = 'https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIPNI/COVID/uf/uf%3DAC/part-00000-93d483f4-9b66-4fd6-a7c5-d617a9d03b7b.c000.csv'

In [17]:
df_vacinas = pd.read_csv('https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIPNI/COVID/uf/uf%3DAC/part-00000-93d483f4-9b66-4fd6-a7c5-d617a9d03b7b.c000.csv', sep = ';')

df_vacinas.head()

C:\Users\luisl\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (7,8) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
0,4ff28e0e-02df-4947-a402-7f6c0993d6c9-i0b0,d025ffced1c17dd83e7ed9615e109b513225afcaf6f7ea...,77,1943-10-27,M,3,PARDA,120025.0,10.0,EPITACIOLANDIA,...,2.0,Faixa Etária,213VCD042Z,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-05-22,2ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
1,a0a56c4b-7252-4098-956f-955759ed500a-i0b0,8c165ecfd823d33ce4d862926a229c17f127b112505697...,15,2006-01-10,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FA9096,PFIZER,Organization/00394544000851,2021-08-06,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
2,8c757ef8-e1a1-4658-ab07-ee7b9865a1fa-i0b0,f6cc130d3ef580e689f97cfe76a6e6124d91b7e928f9ab...,20,2000-12-04,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,9.0,Trabalhadores de Saúde,210110,SINOVAC/BUTANTAN,Organization/61189445000156,2021-04-23,2ª Dose,86,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI
3,a0baa356-deba-4d49-a54c-141141b4b301-i0b0,7a08ec40546abc0f95fdfa4ec1efb22f3f775d7271417d...,47,1974-08-06,F,99,SEM INFORMACAO,120038.0,10.0,PLACIDO DE CASTRO,...,1.0,Comorbidades,216VCD213W,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-08-23,2ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
4,dcf75e5a-fd0f-4cc6-bb98-36c958e156da-i0b0,5aafa70333fc3942d6b51c6bd586cd64bec8103f44c0a5...,47,1974-04-16,F,4,AMARELA,120035.0,10.0,MARECHAL THAUMATURGO,...,6.0,Povos e Comunidades Tradicionais,212VCD001ZVB,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-05-15,1ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI

In [18]:
df_vacinas.shape

(413793, 32)

In [19]:
# 1) Sua solução aqui

df_vacinas.shape[0]

413793

In [20]:
# 2) 

df_vacinas['paciente_id'].nunique()

337037

In [21]:
# 3) 

df_vacinas['vacina_descricao_dose'].unique()

array(['2ª Dose', '1ª Dose', 'Reforço', 'Dose', 'Dose Adicional'],
      dtype=object)

In [22]:
vacinados_1_dose = df_vacinas[df_vacinas['vacina_descricao_dose'] == '1ª Dose']

vacinados_1_dose['paciente_id'].nunique()

202702

In [ ]:
# 3) solução alternativa

In [23]:
# 4) 

vacinados_menor_18 = df_vacinas[df_vacinas['paciente_idade'] < 18]

vacinados_menor_18['paciente_id'].nunique()

44497

In [36]:
# 5) 

df_vacinas['estabelecimento_razaoSocial'].nunique()

46

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [38]:
# DataFrame contendo somente os dados dos estabelecimentos, 
# mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos

def vacinas_menores_18_bool(x):
    if x < 18:
        return True
    else:
        return False

df_vacinas['paciente_idade_bool_menor_18'] = df_vacinas['paciente_idade'].apply(vacinas_menores_18_bool)

df_vacinas[['paciente_idade', 'estabelecimento_razaoSocial', 'paciente_idade_bool_menor_18']]

,paciente_idade,estabelecimento_razaoSocial,paciente_idade_bool_menor_18
0,77,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,False
1,15,PREFEITURA MUNICIPAL DE RIO BRANCO,True
2,20,PREFEITURA MUNICIPAL DE RIO BRANCO,False
3,47,SECRETARIA MUNICIPAL DE SAUDE,False
4,47,PREFEITURA MUNICIPAL DE TARAUACA,False
...,...,...,...
413788,63,PREFEITURA MUNICIPAL DE TARAUACA,False
413789,62,PREFEITURA MUNICIPAL DE RIO BRANCO,False
413790,20,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,False
413791,45,PREFEITURA MUNICIPAL DE RIO BRANCO,False
413792,21,PREFEITURA MUNICIPAL DE RIO BRANCO,False

In [39]:
df_vacinas['paciente_idade_bool_menor_18'].groupby(df_vacinas['estabelecimento_razaoSocial']).sum()

estabelecimento_razaoSocial
61 BIS                                                              0
A M COMERCIO E REPRESENTACOES LTDA                                  0
CENTRO DE DIAGNOSTICOS CITOLAB LTDA                                 0
DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ALTO RIO PURUS        8
DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA                   142
DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO JURUA               302
DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO PURUS                 0
K M OLIVEIRA EIRELI                                                 0
LUIZ AUGUSTO NO BATISTA                                             0
MINISTERIO DA SAUDE                                                20
MUNICIPIO DE MANCIO LIMA                                           13
MUNICIPIO DE MARECHAL THAUMATURGO                                  13
MUNICIPIO DE PORTO WALTER                                          47
MUNICIPIO DE RIO BRANCO                                             0
PORTO WALTER                                                        0
PREFEITURA MUN DE MAL THAUMATURGO                                1194
PREFEITURA MUNICIIPAL DE SENA MADUREIRA                           397
PREFEITURA MUNICIPAL DE ACRELANDIA                                768
PREFEITURA MUNICIPAL DE ASSIS BRASIL                              604
PREFEITURA MUNICIPAL DE BRASILEIA                                1268
PREFEITURA MUNICIPAL DE CAPIXABA                                  456
PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL                          5662
PREFEITURA MUNICIPAL DE EPITACIOLANDIA                            899
PREFEITURA MUNICIPAL DE FEIJO                                    2023
PREFEITURA MUNICIPAL DE JORDAO                                    574
PREFEITURA MUNICIPAL DE MANCIO LIMA                               637
PREFEITURA MUNICIPAL DE MANUEL URBANO                             747
PREFEITURA MUNICIPAL DE PLACIDO DE CASTRO                           0
PREFEITURA MUNICIPAL DE PORTO ACRE                                653
PREFEITURA MUNICIPAL DE PORTO WALTER                              690
PREFEITURA MUNICIPAL DE RIO BRANCO                              21801
PREFEITURA MUNICIPAL DE RODRIGUES ALVES                           856
PREFEITURA MUNICIPAL DE SANTA ROSA DO PURUS                       349
PREFEITURA MUNICIPAL DE SAUDE                                     732
PREFEITURA MUNICIPAL DE SENA MADUREIRA                           2029
PREFEITURA MUNICIPAL DE SENADOR                                     0
PREFEITURA MUNICIPAL DE SENADOR GUIOMARD                         1165
PREFEITURA MUNICIPAL DE TARAUACA                                 2634
PREFEITURA MUNICIPAL DE XAPURI                                   1113
PREFEITURA MUNICIPAL MANCIO LIMA                                   50
PRFEITURA MUNICIPAL DE ACRELANDIA                                   0
REDE DE FRIOS                                                     571
SECRETARIA DE ESTADO DE SAUDE                                     181
SECRETARIA DE ESTADO DE SAUDE DO ACRE                               0
SECRETARIA MUNCIPAL DE SAUDE                                      799
SECRETARIA MUNICIPAL DE SAUDE                                    1101
Name: paciente_idade_bool_menor_18, dtype: int64

In [40]:
df_vacinas['soma_vacinas_menor_18'] = df_vacinas['paciente_idade_bool_menor_18'].groupby(
    df_vacinas['estabelecimento_razaoSocial']).transform(lambda x: x.sum())

df_vacinas.head()

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,paciente_idade_bool,paciente_idade_bool_menor_18,soma_vacinas_menor_18
0,4ff28e0e-02df-4947-a402-7f6c0993d6c9-i0b0,d025ffced1c17dd83e7ed9615e109b513225afcaf6f7ea...,77,1943-10-27,M,3,PARDA,120025.0,10.0,EPITACIOLANDIA,...,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-05-22,2ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI,False,False,899
1,a0a56c4b-7252-4098-956f-955759ed500a-i0b0,8c165ecfd823d33ce4d862926a229c17f127b112505697...,15,2006-01-10,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,PFIZER,Organization/00394544000851,2021-08-06,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI,True,True,21801
2,8c757ef8-e1a1-4658-ab07-ee7b9865a1fa-i0b0,f6cc130d3ef580e689f97cfe76a6e6124d91b7e928f9ab...,20,2000-12-04,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,SINOVAC/BUTANTAN,Organization/61189445000156,2021-04-23,2ª Dose,86,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI,False,False,21801
3,a0baa356-deba-4d49-a54c-141141b4b301-i0b0,7a08ec40546abc0f95fdfa4ec1efb22f3f775d7271417d...,47,1974-08-06,F,99,SEM INFORMACAO,120038.0,10.0,PLACIDO DE CASTRO,...,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-08-23,2ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI,False,False,1101
4,dcf75e5a-fd0f-4cc6-bb98-36c958e156da-i0b0,5aafa70333fc3942d6b51c6bd586cd64bec8103f44c0a5...,47,1974-04-16,F,4,AMARELA,120035.0,10.0,MARECHAL THAUMATURGO,...,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-05-15,1ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI,False,False,2634

In [41]:
df_vacinas_new = df_vacinas[['estabelecimento_razaoSocial', 'soma_vacinas_menor_18']]

df_vacinas_new

                    estabelecimento_razaoSocial  soma_vacinas_menor_18
0        PREFEITURA MUNICIPAL DE EPITACIOLANDIA                    899
1            PREFEITURA MUNICIPAL DE RIO BRANCO                  21801
2            PREFEITURA MUNICIPAL DE RIO BRANCO                  21801
3                 SECRETARIA MUNICIPAL DE SAUDE                   1101
4              PREFEITURA MUNICIPAL DE TARAUACA                   2634
...                                         ...                    ...
413788         PREFEITURA MUNICIPAL DE TARAUACA                   2634
413789       PREFEITURA MUNICIPAL DE RIO BRANCO                  21801
413790  PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL                   5662
413791       PREFEITURA MUNICIPAL DE RIO BRANCO                  21801
413792       PREFEITURA MUNICIPAL DE RIO BRANCO                  21801

[413793 rows x 2 columns]

In [43]:
df_vacinas_new = df_vacinas_new.drop_duplicates()

df_vacinas_new

,estabelecimento_razaoSocial,soma_vacinas_menor_18
0,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,899
1,PREFEITURA MUNICIPAL DE RIO BRANCO,21801
3,SECRETARIA MUNICIPAL DE SAUDE,1101
4,PREFEITURA MUNICIPAL DE TARAUACA,2634
6,PREFEITURA MUNICIPAL DE MANUEL URBANO,747
7,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,5662
11,PREFEITURA MUNICIPAL DE PORTO ACRE,653
17,PREFEITURA MUNICIPAL DE BRASILEIA,1268
18,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,302
32,PREFEITURA MUNICIPAL DE RODRIGUES ALVES,856
33,PREFEITURA MUNICIPAL DE JORDAO,574
34,PREFEITURA MUNICIPAL DE SENADOR GUIOMARD,1165
38,PREFEITURA MUNICIPAL DE CAPIXABA,456
46,PREFEITURA MUNICIPAL DE ACRELANDIA,768
53,PREFEITURA MUNICIPAL DE SENA MADUREIRA,2029
58,PREFEITURA MUNICIPAL DE SANTA ROSA DO PURUS,349
66,PREFEITURA MUNICIIPAL DE SENA MADUREIRA,397
75,PREFEITURA MUNICIPAL DE MANCIO LIMA,637
77,PREFEITURA MUN DE MAL THAUMATURGO,1194
78,PREFEITURA MUNICIPAL DE XAPURI,1113
94,PREFEITURA MUNICIPAL DE FEIJO,2023
107,PREFEITURA MUNICIPAL DE SAUDE,732
110,PREFEITURA MUNICIPAL DE ASSIS BRASIL,604
115,PREFEITURA MUNICIPAL MANCIO LIMA,50
123,REDE DE FRIOS,571
135,MINISTERIO DA SAUDE,20
195,SECRETARIA MUNCIPAL DE SAUDE,799
235,PREFEITURA MUNICIPAL DE PORTO WALTER,690
503,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,142
647,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,0
696,SECRETARIA DE ESTADO DE SAUDE,181
839,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,8
848,MUNICIPIO DE RIO BRANCO,0
1636,MUNICIPIO DE PORTO WALTER,47
2185,SECRETARIA DE ESTADO DE SAUDE DO ACRE,0
3358,MUNICIPIO DE MARECHAL THAUMATURGO,13
3926,MUNICIPIO DE MANCIO LIMA,13
4644,61 BIS,0
11249,PORTO WALTER,0
39891,PREFEITURA MUNICIPAL DE SENADOR,0
57298,A M COMERCIO E REPRESENTACOES LTDA,0
60746,LUIZ AUGUSTO NO BATISTA,0
99971,PREFEITURA MUNICIPAL DE PLACIDO DE CASTRO,0
104127,K M OLIVEIRA EIRELI,0
134830,CENTRO DE DIAGNOSTICOS CITOLAB LTDA,0
388160,PRFEITURA MUNICIPAL DE ACRELANDIA,0

In [45]:
df_vacinas_new.shape

(46, 2)

In [46]:
# 1) 

df_vacinas_menores_18 = df_vacinas[df_vacinas['paciente_idade'] < 18]

df_vacinas_menores_18

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,paciente_idade_bool,paciente_idade_bool_menor_18,soma_vacinas_menor_18
1,a0a56c4b-7252-4098-956f-955759ed500a-i0b0,8c165ecfd823d33ce4d862926a229c17f127b112505697...,15,2006-01-10,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,PFIZER,Organization/00394544000851,2021-08-06,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI,True,True,21801
7,a0bf2424-2010-47b5-9bd2-71df68785462-i0b0,93ce92465d016f68eac3c7e461b604a5c9b5b5e63c3ade...,17,2003-10-29,F,3,PARDA,120020.0,10.0,CRUZEIRO DO SUL,...,PFIZER,Organization/00394544000851,2021-07-31,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI,True,True,5662
9,a0c1d3b2-196c-4820-a169-33ef6d645c9f-i0b0,361b4594f675d4b49d4ee99115b295da2896217f7a5276...,16,2005-04-18,M,4,AMARELA,120034.0,10.0,MANOEL URBANO,...,PFIZER,Organization/00394544000851,2021-09-28,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI,True,True,747
20,cf0aa0bc-0319-4b78-9207-6058607a15a0-i0b0,4e901714e91f89dee5a9e881edc41f26509bd72bb0735f...,16,2005-05-25,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,PFIZER,Organization/00394544000851,2021-10-05,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI,True,True,21801
27,a207633b-f07f-4d13-8f15-66918475deec-i0b0,10bbee40d63434e842b36cf395d7021716b70f366d5b94...,12,2009-07-06,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,PFIZER,Organization/00394544000851,2021-11-17,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI,True,True,21801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413725,8b51d92e-e262-4038-b68c-ffbee4fd78a4-i0b0,faed692d6e191dbfb7a3f8dada5be8dd2a28113661f063...,13,2008-07-07,F,4,AMARELA,120010.0,10.0,BRASILEIA,...,PFIZER,Organization/28290,2021-12-13,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI,True,True,1268
413736,8d41849d-b039-4d49-a3e9-1d945ec801f8-i0b0,a1b0ec8a1bf3c973a4a5f23a7de18a98e7cf9cb1a8fbac...,12,2008-09-28,F,1,BRANCA,120040.0,10.0,RIO BRANCO,...,PFIZER,Organization/00394544000851,2021-08-26,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI,True,True,21801
413742,8db7e55d-670c-4c56-ac76-e40b32e8c6fb-i0b0,2b635add4b2f0979b4889f81d3837a6fc639d64bb52014...,13,2007-09-23,M,5,INDIGENA,120043.0,10.0,SANTA ROSA DO PURUS,...,PFIZER,Organization/00394544000851,2021-08-25,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI,True,True,349
413762,92f34126-3c53-4206-b999-dea4e7419264-i0b0,0f2e7f139b1aec21fd238cc7709d2d24373b15b10f0b0e...,13,2008-06-11,M,3,PARDA,120038.0,10.0,PLACIDO DE CASTRO,...,PFIZER,Organization/00394544000851,2021-11-18,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI,True,True,1101
413780,95eec920-502c-4a9c-9ed6-19ad3c36584a-i0b0,94f1a63087059f21a27c92218e61ee465db807e474bf56...,15,2006-03-13,F,3,PARDA,120030.0,10.0,FEIJO,...,PFIZER,Organization/00394544000851,2021-11-09,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI,True,True,2023

In [51]:
# 2)

df_vacinas_colunas = df_vacinas.columns

df_vacinas_colunas

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_dataNascimento', 'paciente_enumSexoBiologico',
       'paciente_racaCor_codigo', 'paciente_racaCor_valor',
       'paciente_endereco_coIbgeMunicipio', 'paciente_endereco_coPais',
       'paciente_endereco_nmMunicipio', 'paciente_endereco_nmPais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumNacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaoSocial', 'estalecimento_noFantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoAtendimento_codigo',
       'vacina_grupoAtendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataAplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem', 'paciente_idade_bool', 'paciente_idade_bool_menor_18',
       'soma_vacinas_menor_18'],
      dtype='object')

In [54]:
# 3) 

df_vacinas_menores_18['vacina_categoria_nome'].count()

46201